{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.ec2_security_group', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.ec2_security_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1808, in <module>\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1790, in main\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1653, in ensure_present\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1089, in add_new_permissions\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1102, in authorize\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/errors.py\", line 41, in handler\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 119, in _retry_wrapper\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 68, in _retry_func\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py\", line 1238, in authorize_security_group_ingress\nKeyError: 'Return'\n",
  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1753338918.6642277-217-141010536146931/AnsiballZ_ec2_security_group.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.amazon.aws.plugins.modules.ec2_security_group', init_globals=dict(_module_fqn='ansible_collections.amazon.aws.plugins.modules.ec2_security_group', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1808, in <module>\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1790, in main\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1653, in ensure_present\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1089, in add_new_permissions\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/modules/ec2_security_group.py\", line 1102, in authorize\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/errors.py\", line 41, in handler\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 119, in _retry_wrapper\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/cloud.py\", line 68, in _retry_func\n  File \"/tmp/ansible_amazon.aws.ec2_security_group_payload_05u0jm63/ansible_amazon.aws.ec2_security_group_payload.zip/ansible_collections/amazon/aws/plugins/module_utils/ec2.py\", line 1238, in authorize_security_group_ingress\nKeyError: 'Return'\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": null,
  "changed": false
}
